create extension if not exists pgcrypto;

create table if not exists public.users (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null unique,
    password_hash text,
    telegram_chat_id bigint null,
    notes jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.schedules (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users (id) on delete cascade,
    day_of_week smallint not null check (day_of_week between 1 and 7),
    lessons jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, day_of_week)
);

create table if not exists public.files (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users (id) on delete cascade,
    file_name text not null,
    file_url text not null,
    created_at timestamptz not null default now()
);

alter table if exists public.users
    alter column telegram_chat_id type bigint using nullif(telegram_chat_id::text, '')::bigint;

alter table if exists public.users
    add column if not exists notes jsonb not null default '{}'::jsonb;

create index if not exists schedules_user_id_idx on public.schedules (user_id);
create index if not exists files_user_id_idx on public.files (user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists schedules_set_updated_at on public.schedules;
create trigger schedules_set_updated_at
before update on public.schedules
for each row execute function public.set_updated_at();
