create extension if not exists pgcrypto;

create table if not exists public.users (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null unique,
    password_hash text,
    telegram_chat_id bigint null,
    notes jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.schedules (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users (id) on delete cascade,
    week_number smallint not null default 1 check (week_number between 1 and 52),
    day_of_week smallint not null check (day_of_week between 1 and 7),
    lessons jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, week_number, day_of_week)
);

create table if not exists public.files (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users (id) on delete cascade,
    file_hash text not null,
    file_name text not null,
    file_url text not null,
    created_at timestamptz not null default now(),
    unique (user_id, file_hash)
);

create table if not exists public.telegram_link_tokens (
    token text primary key,
    user_id uuid not null references public.users (id) on delete cascade,
    email text,
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.document_chunks (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users (id) on delete cascade,
    file_hash text not null,
    file_name text not null,
    chunk_index integer not null,
    page_number integer not null default 0,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table if exists public.users
    alter column telegram_chat_id type bigint using nullif(telegram_chat_id::text, '')::bigint;

alter table if exists public.users
    add column if not exists notes jsonb not null default '{}'::jsonb;

alter table if exists public.schedules
    add column if not exists week_number smallint not null default 1;

alter table if exists public.files
    add column if not exists file_hash text;

create index if not exists schedules_user_id_idx on public.schedules (user_id);
create index if not exists schedules_user_week_idx on public.schedules (user_id, week_number);
create index if not exists files_user_id_idx on public.files (user_id);
create index if not exists document_chunks_user_file_idx on public.document_chunks (user_id, file_hash);
create index if not exists telegram_link_tokens_user_idx on public.telegram_link_tokens (user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists schedules_set_updated_at on public.schedules;
create trigger schedules_set_updated_at
before update on public.schedules
for each row execute function public.set_updated_at();
